### ISSUE TITLE
Proposal: functions should specify OS constraints

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#101]
## Expected Behaviour

Deploying a function on a mixed-OS cluster should be possible - where a Windows container is scheduled correctly.

## Current Behaviour

The task will be scheduled randomly - possibly on a Linux host.

## Possible Solution

Add a default constraint to Linux and allow this to be overridden in the *deploy function* endpoint. A change to the CLI may also make sense later down the line.

Checkpoints:

* encompasses the RESTFul schema

Schema https://github.com/alexellis/faas/blob/master/gateway/requests/requests.go#L7

* Includes an update to the swagger API

* Covers both Kubernetes and Swarm

**Comment by glyif** [comment]
I can try and take on this issue :)

**Comment by alexellis** [comment]
I think @rgee0 started work on this.. is that still in-progress?

@glyif thanks very much for the offer of help, much appreciated. Can you get in touch with your email address for an invite to Slack?

**Comment by glyif** [comment]
@alexellis my email is 122@holbertonschool.com :)

**Comment by alexellis** [comment]
@rgee0 @glyif what's your bandwidth like for this week?

**Comment by alexellis** [comment]
In lieu of this being completed #160 makes the default experience better by ensuring Linux containers are scheduled on Linux nodes.

**Comment by alexellis** [comment]
Now available in the FaaS-CLI by passing --constraint or using a `constraints` element for a function. @glyif @rgee0 fancy writing a quick guide/blog?
