### ISSUE TITLE
url_ping sample function in README.md fails with readdirent: invalid argument

### ISSUE THREAD

**Issue by bsommers** [alexellis/faas#105]
## Expected Behaviour
Expected faas-cli to successfully build the function with:
``````
faas-cli -action build -f ./urlping.yaml
``````
## Current Behaviour

`````
.
.
.
cp - ./template/python/requirements.txt ./build/url_ping/requirements.txt
cp - ./template/python/function/handler.py ./build/url_ping/function/handler.py
2017/07/10 10:51:14 readdirent: invalid argument
`````

## Steps to Reproduce (for bugs)

1.  create urlping.yaml as described in README.md
2.  create ./sample/url_ping as described in README.md
3.  execute faas-cli -action build -f ./urlping.yaml

## Context
Trying the sample code to get FAAS working in my environment

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project:
N/A

**Comment by alexellis** [comment]
You need the template folder - v0.4 of the CLI will bring that down automatically if it's missing. For now can you `git clone https://github.com/alexellis/faas-cli` and run the command from inside that folder. Brew is lagging behind if you used that to get the CLI.

**Comment by bsommers** [comment]
Thanks.  That did it.   I must have installed faas-cli using brew when I first start with it 2 weeks ago.

Good stuff!   Keep up the great work!

**Comment by alexellis** [comment]
Closing this issue for now @bsommers thanks for the feedback and I've sent you an invite to Slack.
