### ISSUE TITLE
API / UI - use Prometheus API (not local counter) for stats

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#116]
## Expected Behaviour

Now that the Gateway can be load-balanced an invocation count should cover the count across all of the gateways.

## Current Behaviour

For Swarm it shows the current gateway instance since we're reading the local counter

For Kubernetes it shows as empty

## Possible Solution

Query the Prometheus API from the gateway:

PromQL example:

```
gateway_function_invocation_total{}
```

Concerns:

* creates a circular dependency since the gateway is a scrape target
* scrape interval is around 5-15s meaning we won't see the invocation count increase live.

* this data needs to be overlaid on top of the "list functions" response from Swarm or the external gateway - See: `faasHandlers.ListFunctions` in `server.go` for the FaaS gateway

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Both

**Comment by johnmccabe** [comment]
I'll pick this one up @alexellis

**Comment by alexellis** [comment]
Here's a sample for parsing the Prometheus format from your local gateway.

```go
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

func main() {
	client := http.Client{}
	req, reqErr := http.NewRequest("GET", "http://localhost:9090/api/v1/query/?query=gateway_function_invocation_total", nil)
	if reqErr != nil {
		log.Println(reqErr)
	}

	res, getErr := client.Do(req)
	if getErr != nil {
		fmt.Fprintln(os.Stderr, getErr)
		return
	}
	defer res.Body.Close()
	bytesOut, readErr := ioutil.ReadAll(res.Body)
	if readErr != nil {
		fmt.Fprintln(os.Stderr, readErr)
	}

	var values VectorQueryResponse

	unmarshalErr := json.Unmarshal(bytesOut, &values)

	if unmarshalErr != nil {
		fmt.Fprintln(os.Stderr, unmarshalErr)
	}

	for _, result := range values.Data.Result {
		fmt.Println(result.Metric.FunctionName, result.Metric.Code, result.Value[1])
	}
}

type VectorQueryResponse struct {
	Data struct {
		Result []struct {
			Metric struct {
				Code         string `json:"code"`
				FunctionName string `json:"function_name"`
			}
			Value []interface{}
		}
	}
}
```

**Comment by johnmccabe** [comment]
Just dumping in some notes.

You can reproduce the behaviour that needs fixed as follows (on Docker Swarm):
- Scale the gateway to 3 instances
```
docker service scale func_gateway=3
```
- Open the gateway dashboard in an incognito and non-incognito tab, and invoke the echoit function a few times in each window, you should see that the counts increment independently as you've got a sticky session with different instances.
