### ISSUE TITLE
Enhancement - FaaS UI to use mono-spaced font for request/response

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#135]
## Issue

The FaaS UI can be used to invoke functions on the cluster - it has two textboxes for request/response - both are using the default Angular material theme's font.

### Proposed fix

Either find a way to force/override the Angular material font or embed a light-weight JavaScript code editor.

**Comment by fabienheureux** [comment]
[Roboto Mono](https://fonts.google.com/selection?selection.family=Crimson+Text%7CRoboto+Mono) could fit Material UI design, an be easily added to the project through google font import already in place: https://github.com/alexellis/faas/blob/19699d5e799f8ded9995cef0ded8f6558f53643c/gateway/assets/index.html#L4

**Comment by alexellis** [comment]
That sounds like a good approach @fabienheureux. Can you try it out and share a screenshot in this issue?

**Comment by fabienheureux** [comment]
Sure, will share something on my lunch break 😉

**Comment by alexellis** [comment]
If you think the changes are good, you can just rebuild the container and deploy again.

./build.sh in gateway folder

then update docker-compose.yml to add the tag "latest-dev" instead of "0.6.0" (or whatever it is set to) for the gateway.

**Comment by alexellis** [comment]
Fixed in #140
