### ISSUE TITLE
Blog + function - Node.js

### ISSUE THREAD

**Issue by glyif** [alexellis/faas#136]
I'll be writing a simple Node.js function that takes in a URI and takes a screenshot the page and uploads the file to a s3 bucket.

Afterwards, I'll write a blog on about the function, how to deploy and run it using OpenFaas, and my thoughts on all the things.

The purpose is to for me to familiarize myself with the project and write a bomb blog post.

**Comment by alexellis** [comment]
For Node.js you can follow the Python guide and replace the word python for node.

https://blog.alexellis.io/first-faas-python-function/

**Comment by alexellis** [comment]
Hey @glyif are you still working on this? Do you need anything?

**Comment by alexellis** [comment]
Closing..
