### ISSUE TITLE
Proposal: Enable "Remove function" in FaaS UI

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/faas#137]
## Issue

It is not possible to delete functions via the FaaS UI.

### Proposed fix

Add an Angular card with a delete button below the Invoke function card. See [this comment](https://github.com/alexellis/faas/issues/137#issuecomment-324252757) for some UX direction on implementation.

**Comment by alexellis** [comment]
@johnmccabe Please can you put together screenshot in paint or whatever works and attach?

**Comment by johnmccabe** [comment]
<img width="1084" alt="delete_idea" src="https://user-images.githubusercontent.com/83862/29536146-92d6a144-86b4-11e7-93fd-7c80e76d563f.png">

@alexellis this good for you?

**Comment by rgee0** [comment]
While we've got this page open do we want to change FaaS to OpenFaaS in the top left too?

**Comment by alexellis** [comment]
@johnmccabe  It's way too big and easy to hit. Perhaps this should be on a pop-up dialog via a "..." break-out.

**Comment by alexellis** [comment]
@rgee0 good point, can you put that suggestion on issue #123 and ping @glyif?

**Comment by johnmccabe** [comment]
<img width="1084" alt="dropdown_delete_idea" src="https://user-images.githubusercontent.com/83862/29538358-57a78134-86bd-11e7-85a0-a5d8eb0c98e3.png">

@alexellis with a dropdown, the wide delete button in a card seems like the more material-ly one to me fwiw, very subjective ofc :)

**Comment by glyif** [comment]
we can also do something like this so peeps don't accidentally delete

<img width="1013" alt="screen shot 2017-08-21 at 2 11 15 pm" src="https://user-images.githubusercontent.com/25441110/29538431-a2081934-867a-11e7-9580-0a4f7e766711.png">

**Comment by alexellis** [comment]
If you want to mix both you could but it on the row with Invoke, but have the pop-up for confirming. I think the huge red button in the first screenshot could draw the eye too much and it'll be hard to find when you invoke a function (i.e. it will be pushed very far down the screen)

**Comment by johnmccabe** [comment]
And with an elipsis (looks cleaner)

![dropdown](https://user-images.githubusercontent.com/83862/29538671-bc8a9298-86be-11e7-8876-c851cb60fda7.jpg)
![dropdown](https://user-images.githubusercontent.com/83862/29538642-9b8bc7ec-86be-11e7-9d5b-bce981c76a5d.jpg)

**Comment by rgee0** [comment]
I'd say the delete button needs to be away from the function output. Top right feels better to me.

**Comment by fabienheureux** [comment]
Hi, my thoughts on this issue: 
- I agree with the dropdown solution, that let delete option appears
- I would place all action buttons at the same place, it makes more sense (invoke, actions, and maybe more in the future)
- Use label and/or pictograms usually helps user to understand the UI (e.g.: http://fontawesome.io)

An attached screenshot with what I think quite appropriate (did not saw @johnmccabe proposition at first, that is quite similar):  
<img width="1104" alt="screenshot 2017-08-23 09 40 09" src="https://user-images.githubusercontent.com/1702255/29604258-377e5984-87e7-11e7-802f-2e2176829437.png">
- The delete button is in a dropdown as @alexellis suggested

**Comment by alexellis** [comment]
Can we move forward with the last suggestion - but with a caveat:

* Add the contextual menu top right
* Keep invoke where it is and revisit after adding actions drop-down menu

**Comment by alexellis** [comment]
@fabienheureux - how do you feel about implementing the UI? cc @aafrey

**Comment by alexellis** [comment]
@fabienheureux ping 🏓

**Comment by fabienheureux** [comment]
@alexellis sure, I will work on this next week 👍

**Comment by kenfdev** [comment]
![func_deletion](https://user-images.githubusercontent.com/3941889/30253527-142e20e2-96c2-11e7-8089-c1ec2a8abbe7.gif)

Hi, I didn't realize this thread and was thinking about deletion, too. I basically agree with the final suggestions but how about making the "ACTIONS" button an ellipsis icon like @rgee0 suggests?

Here is a sample I was making.  But including the above suggestions, the trash icon would become an ellipsis and also, it would become a dropdown.

@fabienheureux I could have a look at this today or tomorrow (JST timezone) so feel free to ping me  if I can help!

**Comment by alexellis** [comment]
I like this final gif - @kenfdev if you want to commit this in a PR I think we could just merge it and close this issue.

**Comment by kenfdev** [comment]
@alexellis No problem. I think I can implement it tonight (GMT+9)

**Comment by alexellis** [comment]
Merged. Thank you to everyone on the thread for your contribution and to @kenfdev for the PR.
