### ISSUE TITLE
Help: How do you handle system level dependencies?

### ISSUE THREAD

**Issue by xichengc** [alexellis/faas#141]
## Issue
Some of my function's dependencies are not just python-level dependencies. What do I need to do to add system level dependencies such as GCC?

**Comment by alexellis** [comment]
Hi there :-) you can edit the templates directly to suit your needs. I needed GCC for python-pptx - my example is here:

https://github.com/alexellis/faas-office-sample

Does this help? Also I think this needs documenting in the repo. 

Alex

**Comment by xichengc** [comment]
Thanks @alexellis 
I can see there are 6 template directories in total: `csharp  node  node-armhf  python  python-armhf  ruby`

Is it possible to add a new template directory, say `custom-python` with a custom Dockerfile and somehow specify it in the `stack.yml`? I am trying keep all the existing templates as-is. :-)

**Comment by alexellis** [comment]
If you could head over to the example I sent you'll see what you need to do from there.

* In the example I just have a template folder with a "python" template inside

* Here is the modified Dockerfile and template in the "template/python" folder:

https://github.com/alexellis/faas-office-sample/blob/master/template/python/Dockerfile

* The base image was changed to Debian

Each folder can have its own set of templates.. like:

For instance:

./my_stack.yml
./handlers/function1
./handlers/function2
./templates/python

If you don't want to use templating but would like to use a completely custom Docker you can just build it with `docker build -t function_name .` and deploy via the stack file.

```
functions:
  function_name_here:
    skip_build: true
    fprocess: python main.py
    image: xichengc/function_name_here
```

**Comment by xichengc** [comment]
Thanks @alexellis for the help.
I was able to use the custom template for my function. So I guess the templates located in function directories override the global templates. 

I am closing this issue. 
I still have some questions non-related to the topics covered in this issue. Not sure if it's OK for us to connect on Slack? Thanks!

**Comment by alexellis** [comment]
Please share your email address and I'll send an invite

**Comment by alexellis** [comment]
I've sent an invite to your huawei.com address.

**Comment by xichengc** [comment]
Sorry that email address expired long time ago. I forgot to update it. Could you send an invite to mr.xchang@gmail.com ?
Thanks.
