### ISSUE TITLE
ERROR: unsatisfiable constraints: from faas-cli -action build -f ./urlping.yaml

### ISSUE THREAD

**Issue by tijoytom** [alexellis/faas#146]
I am following the readme and trying to get my first function running , but hit the below error when trying to build the image 

**-> sudo faas-cli -action build -f ./urlping.yaml**

 ---> Running in 1075c04bc182
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
The command '/bin/sh -c apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/alexellis/faas/releases/download/0.5.8-alpha/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache' returned a non-zero code: 1

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.06.1-ce, build 874a737

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
  Linux Ubuntu 14.04
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @tijoytom 

Thanks trying OpenFaaS 👍 ! I've just tried this myself again and it works fine, so I suspect this may be an issue with your internet connection. I also haven't run the faas-cli as `sudo`.

```
Step 2/15 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/alexellis/faas/releases/download/0.5.8-alpha/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Running in 9a426aa71f45
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libssh2 (1.7.0-r0)
(2/3) Installing libcurl (7.55.0-r0)
(3/3) Installing curl (7.55.0-r0)
Executing busybox-1.24.2-r13.trigger
OK: 32 MiB in 35 packages
Pulling watchdog binary from Github.
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/3) Purging curl (7.55.0-r0)
(2/3) Purging libcurl (7.55.0-r0)
(3/3) Purging libssh2 (1.7.0-r0)
Executing busybox-1.24.2-r13.trigger
OK: 31 MiB in 32 packages
 ---> 26694207f995
```

Here's two things you can try:

* Force an update on the base Python image:

`$ docker pull python:2.7-alpine`

* Wipe cache

Use a flag of `--no-cache=true` on the `faas-cli`

Please let us know how you get on.

**Comment by alexellis** [comment]
Hi we couldn't reproduce the issue, I'd check your networking and try again. Let us know how it goes and feel free to re-open.

**Comment by tijoytom** [comment]
@alexellis Thanks , I was able to get it working on my windows machine , no idea what's wrong with the Ubuntu box..

**Comment by alexellis** [comment]
That's good to hear. I'd suggest trying it again, or maybe provisioning a quick droplet on Digital Ocean?

**Comment by ndsun** [comment]
hi,I got the error,too.
It's the log:
[0] > Building hello-python.
Clearing temporary build folder: ./build/hello-python/
Preparing ./hello-python/ ./build/hello-python/function
Building: hello-python:latest with python template. Please wait..
Sending build context to Docker daemon  8.192kB
Step 1/25 : FROM python:2.7-alpine
 ---> c98d9ddf345d
Step 2/25 : ARG ADDITIONAL_PACKAGE
 ---> Running in ac04aa392a84
Removing intermediate container ac04aa392a84
 ---> e12c355af0d7
Step 3/25 : RUN apk --no-cache add curl ${ADDITIONAL_PACKAGE}     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Running in cefce1ea66f8
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
The command '/bin/sh -c apk --no-cache add curl ${ADDITIONAL_PACKAGE}     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache' returned a non-zero code: 1
2018/10/31 17:15:20 ERROR - Could not execute command: [docker build --no-cache -t hello-python:latest .]

**Comment by alexellis** [comment]
This was logged one year ago, do you still have it? We can't reproduce any issue like this so I wondered if you have a restrictive firewall or corporate network? 

Alex

**Comment by flaviocysne** [comment]
> Hi @tijoytom
> 
> Thanks trying OpenFaaS  ! I've just tried this myself again and it works fine, so I suspect this may be an issue with your internet connection. I also haven't run the faas-cli as `sudo`.
> 
> ```
> Step 2/15 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/alexellis/faas/releases/download/0.5.8-alpha/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
>  ---> Running in 9a426aa71f45
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
> (1/3) Installing libssh2 (1.7.0-r0)
> (2/3) Installing libcurl (7.55.0-r0)
> (3/3) Installing curl (7.55.0-r0)
> Executing busybox-1.24.2-r13.trigger
> OK: 32 MiB in 35 packages
> Pulling watchdog binary from Github.
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
> (1/3) Purging curl (7.55.0-r0)
> (2/3) Purging libcurl (7.55.0-r0)
> (3/3) Purging libssh2 (1.7.0-r0)
> Executing busybox-1.24.2-r13.trigger
> OK: 31 MiB in 32 packages
>  ---> 26694207f995
> ```
> 
> Here's two things you can try:
> 
> * Force an update on the base Python image:
> 
> `$ docker pull python:2.7-alpine`
> 
> * Wipe cache
> 
> Use a flag of `--no-cache=true` on the `faas-cli`
> 
> Please let us know how you get on.

Just as reference, I ran into this error and I'm under a corporate/firewall network. I ran the command again with the `--no-cache=true` directive and it did the work. I didn't run the `$ docker pull python:2.7-alpine` command though. Hope it helps.
