### ISSUE TITLE
Bug in README.md sample code, ./sample/url_ping not found, path ./sample/url-ping exists

### ISSUE THREAD

**Issue by ems5311** [alexellis/faas#147]
I believe that the path is incorrect in the README sample code for the example function YAML file - urlping.yaml. Currently the handler section of the url_ping function in the urlping.yaml file points to `./sample/url_ping`, although in the project faas-cli, there is a folder called `./sample/url-ping`.

I have a fix for this in my local branch:

[https://github.com/ems5311/faas/commit/965339ba7f2a6a34387bb51a5313ff622a3d8caf](https://github.com/ems5311/faas/commit/965339ba7f2a6a34387bb51a5313ff622a3d8caf)

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
no

* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 1604 lts

* Link to your project or a code example to reproduce issue:
https://github.com/ems5311/faas/commit/965339ba7f2a6a34387bb51a5313ff622a3d8caf

**Comment by alexellis** [comment]
Hi, thanks for trying OpenFaaS. I've updated the reference from url_ping to url-ping to match the recent change in the GitHub repo.

**Comment by alexellis** [comment]
Fixed in https://github.com/alexellis/faas/commit/5254f47c26f0e602185d4b39a1a8f9ef89803ae7 👍

**Comment by ems5311** [comment]
Thanks Alex!
