### ISSUE TITLE
Proposal: How do I contribute sample-functions for R lang?

### ISSUE THREAD

**Issue by mrchypark** [alexellis/faas#152]
I find out sample-functions language have docker image like functions/base:python-2.7-alpine.
I want to contribute for R language which support dockerhub image like functions/base:R-3.4.1-alpine.

## Expected Behaviour

I want to run R lang based functions for faas using yml like lang: R
Before that, i contribute code for sample first.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thanks I had a chat with the other maintainers and we're happy to accept the change.

**Comment by alexellis** [comment]
Thank you for this!
