### ISSUE TITLE
Slack channel invites

### ISSUE THREAD

**Issue by ivdelchev** [alexellis/faas#156]
The readme says this is the preferred way to request access to the slack channel so I am opening this issue. Could I get an invite? I am dealing with Docker on a daily basis on production and for fun and have already played with FaaS a bit.

**Comment by alexellis** [comment]
Hi @ivdelchev - you'd be more than welcome - please send an email over to alex@openfaas.com

**Comment by alexellis** [comment]
Invite sent - thanks for joining!
