### ISSUE TITLE
Document/expose the minimum API required to be 'watchdog compatible'

### ISSUE THREAD

**Issue by alias1** [alexellis/faas#162]
I would like to enable my golang executable to be directly 'watchdog compatible', without needing to include the separate watchdog binary in my container.

## Expected Behaviour

Have the minimal API/interface of the watchdog documented/exposed as a library so that I can embed it directly into my golang executable.

## Current Behaviour

I believe the currently recommended way is to just use the watchdog. I could probably read through the internals to figure out how I could implement in my own code, but that seems like overkill.

## Possible Solution

Document or expose the minimum API/interface required for a program to expose to be 'watchdog compatible'.

## Steps to Reproduce (for bugs)

N/A

## Context

I have a minimised, static compiled, packed golang executable running in a `FROM scratch` container. Adding the watchdog process adds an extra ~6mb to my ~1mb container, and feels like it needlessly complicates things.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): 17.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* Link to your project or a code example to reproduce issue: N/A

**Comment by alexellis** [comment]
This is an unsupported configuration, but you can expose port 8080 and OpenFaaS should treat your container the same as if it was running the watchdog.

**Comment by alias1** [comment]
Program already includes net packages (static linked, packed with `upx`), but the hard timeout is something I probably can't enforce from the single executable. Good to know that I can get the 'basic' functionality just by exposing on `8080` though :)

**Comment by alexellis** [comment]
Note added here https://github.com/alexellis/faas/blob/master/watchdog/README.md

Closing issue - feel free to keep discussion going 👍

**Comment by alias1** [comment]
Awesome, thanks :)
