### ISSUE TITLE
Proposal: Reduce the size of the watchdog executable

### ISSUE THREAD

**Issue by alias1** [alexellis/faas#163]
## Expected Behaviour

Through a combination of multi-stage builds, and some other tricks (static compilation, packing), it would be possible to reduce the size of the current watchdog executable. For large legacy programs, the current size may not make much of a difference, but for a current project i'm working on, the watchdog is ~6 times larger than my actual program.

This is the multi-stage Dockerfile I currently use to minimize my end golang binary. A similar process should work for the watchdog:
* https://github.com/alias1/gobuster/blob/docker/Dockerfile

**Comment by alexellis** [comment]
I'm not sure why this would be a concern, especially if it's a cached and shared layer between your functions. However if you can optimise the watchdog further (it already uses a multi-stage build in so much as a lone binary is extracted from a build-time container) then I think we would consider a PR. It also needs to work on ARM / Linux and Windows.

**Comment by johnmccabe** [comment]
+1 on using `upx` to shrink the watchdog, I've used it for go binaries linked against C++ libs in the past, what size reduction are you getting against the watchdog?

**Comment by alias1** [comment]
From the code I read (maybe wasn't latest) it used a multi-stage build styled pattern, but not the new multi-stage build Dockerfile syntax.

I suppose at the end of the day it doesn't represent a massive issue, but I like to optimize things where they can be. 

Running a quick test:
```
FROM alpine:edge AS pack-env
WORKDIR /
RUN apk add --no-cache upx
ADD https://github.com/alexellis/faas/releases/download/0.6.2/fwatchdog /fwatchdog
RUN [ "chmod", "+x", "/fwatchdog" ]
RUN upx --brute fwatchdog -ofwatchdog.upx
```

Inspecting in that container
```
-rwx--x--x    1 root     root        5.7M Aug 29 18:49 fwatchdog
-rwx--x--x    1 root     root        1.4M Aug 29 18:49 fwatchdog.upx
```

**Comment by alexellis** [comment]
I don't want to strip debug info or line numbers.

Here's what we can do with a suggestion via @justincormack 

```
Step 12/14 : RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-s -w" -installsuffix cgo -o watchdog-1 . && du -h ./watchdog-1
 ---> Running in a2951bbeb9fd
3.7M	./watchdog-1
 ---> 31df59703557
Removing intermediate container a2951bbeb9fd
```

He also suggested looking at removing the log package due to its unicode/utf-8 support.

**Comment by alias1** [comment]
Nice. I would have to read the specifics on upx again, but I think you can still get the size reductions without losing the debug info (though don't quote me on that), at the cost of very slightly increasing delay on first-run.

**Comment by alexellis** [comment]
In that context what does `upx` remove? We've tried a minimal HTTP server with the new flags and it still comes out at 3.8M

```
package main

import (
        "net/http"
        "strconv"
)

func rootHandler(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "text/html")
        w.WriteHeader(http.StatusOK)
        data := []byte("test")
        w.Header().Set("Content-Length", strconv.Itoa(len(data)))
        _, _ = w.Write(data)
}

func main() {
        http.HandleFunc("/", rootHandler)
        _ = http.ListenAndServe(":8080", nil)
}
```

**Comment by alias1** [comment]
I think it's more about compression than stripping things:
* https://upx.github.io/

**Comment by alexellis** [comment]
I'll close this issue once PR #164 is merged. If you would like to research using `upx` perhaps we can provide an alternative instructions for its usage or link to a blog / GitHub repo etc.

**Comment by alexellis** [comment]
Closing. Let's revisit the `upx` idea later on. I'll mark this as "revisit"

**Comment by alias1** [comment]
Sounds good to me :)
