### ISSUE TITLE
UI portal on 8080 only white screen

### ISSUE THREAD

**Issue by macneib** [alexellis/faas#17]
This way cool, and thanks for posting this project!

I ran the quickstart, and again on my local machine, however I wasn't able to successfully bring the UI portal up.  
1) Cloned mater branch
2 ) `docker swarm init --advertise-addr=$(ifconfig eth0| grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}') &&   git clone https://github.com/alexellis/faas &&   cd faas &&   ./deploy_stack.sh &&   docker service ls`
3) used curl to verify the stack was consumer web events
4) checked prom to which came up without issues
5) checked  AlertManager also no issues.
6) tried http://localhost:8080 and I can only see a white screen, even though I can post events.

Curious if you have any tips to get to the UX screen.
TIA!

**Comment by macneib** [comment]
upon further investigation I suspect the issue arises from the Docker file

` faas/gateway/Dockerfile` line 11

```
COPY assets assets
```

should be

```
COPY assets assets/
```

**Comment by alexellis** [comment]
Thanks for the feedback on this - please see note on: https://github.com/alexellis/faas/pull/18

Btw you can create your own function two ways:
* through the stack file and running `docker stack deploy`
* through a new pop-up in the UI

The image I've pushed will now contain the "new function" popup and you can checkout [this]() as an example on how to create one with the base AlpineFunction image or any other image with your own code. Basically any Docker container plus the `fwatchdog` process.

**Comment by macneib** [comment]
works now thanks!

**Comment by alexellis** [comment]
Awesome, this will also work on your regular Docker installation just need at least 1.13. Do you have any pet projects or images you could try with FaaS?

**Comment by macneib** [comment]
Currently, my plan to to do some experiments with a few esp8266 modules and FaaS to see if I can do multi-room temperature measurements.  I didn't want to go overkill on a stack just to collect temperature data, this faas stack is pretty much much perfect for me.  I'll post some snippets once I get things up and running.  Thanks again.
