### ISSUE TITLE
add line http.HandleFunc("/README", readmeRequestHandler(&config))

### ISSUE THREAD

**Issue by clh8801** [alexellis/faas#177]
https://github.com/alexellis/faas/blob/b9be8293a84bcdac11e845dc613ab12d6fcd0a90/watchdog/main.go#L253
return the `README` file content to the apigateway

**Comment by alexellis** [comment]
Please fill out the whole template. What is this change for?

**Comment by clh8801** [comment]
the file README.md is the document of fprocess,'/README' return the document content,it's will If the fprocess version changes frequently.

**Comment by alexellis** [comment]
This isn't something we are planning on supporting - so I'll close the issue. Do we need to make the versioning or documentation better?
