### ISSUE TITLE
nothing wrong when deploy, but cannot access localhost:8080

### ISSUE THREAD

**Issue by metrue** [alexellis/faas#179]
## Expected Behaviour
```
git clone https://github.com/alexellis/faas
cd fass
./deploy_stash.sh
```
nothing was wroing after above, but localhost:8080 could not be accessiable.
```
This site can’t be reached

localhost refused to connect.
Did you mean http://localhost-8080.com/?
Search Google for localhost 8080
ERR_CONNECTION_REFUSED
```

## Possible Solution
document improvement, I am totally new to this project, after reading the README.md, I'd like to try a simple demo. 

## Steps to Reproduce (for bugs)

```
git clone https://github.com/alexellis/faas
cd fass
./deploy_stash.sh
```
then open http://localhost:8080

## Your Environment
Docker version 17.06.2-ce, build cec0b72

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Yes, I am using docker swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux li1705-191 4.9.15-x86_64-linode81 #1 SMP Fri Mar 17 09:47:36 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexellis** [comment]
It's ./deploy_stack.sh - please provide some debug info. Also it's not localhost.com? Try http://127.0.0.1:8080

https://github.com/alexellis/faas/blob/master/guide/deployment_swarm.md

**Comment by alexellis** [comment]
Are you doing this on your laptop or the cloud? If it's on a remote host you will absolutely need to use the public IP of that host to access OpenFaaS

**Comment by johnmccabe** [comment]
@alexellis looks like linode from the uname output

**Comment by jmkhael** [comment]
In addition to @alexellis suggestions, try another browser: I had problems with localhost address with chrome. try using another browser if you are using chrome.

Try using your machine name too.
check your `/etc/hosts` if you have 

```
127.0.0.1       localhost
127.0.0.1       localhost.
```

**Comment by mjbright** [comment]
Otherwise performing
    docker stack ps func

might give you information about tasks which are failing in your "func"
stack.

**Comment by johnmccabe** [comment]
Derek add label: question

**Comment by alexellis** [comment]
@metrue - we're going to close the issue, but please feel free to keep commenting.

**Comment by metrue** [comment]
@alexellis @jmkhael @mjbright 

sorry for my late response, internet not work when I was on vacation few days ago.

thanks for you guys' explanation,  I will try it again, will update if it still not work.

**Comment by alexellis** [comment]
Ok thanks for letting us know
