### ISSUE TITLE
Tear-down question for Docker Swarm

### ISSUE THREAD

**Issue by ems5311** [alexellis/faas#189]
When I run `docker stack rm <stack name>`, I would expect all of the functions to get deleted, but it doesn't seem to do so:

```
s@s-GA-78LMT-USB3-6-0:~/github/go/src/github.com/alexellis/faas-cli$ docker stack rm func
Removing service func_alertmanager
Removing service func_base64
Removing service func_decodebase64
Removing service func_echoit
Removing service func_gateway
Removing service func_hubstats
Removing service func_markdown
Removing service func_nodeinfo
Removing service func_prometheus
Removing service func_webhookstash
Removing service func_wordcount
Removing network func_functions
Failed to remove network yxjfuqcxs8dxh35ve3dx1abv9: Error response from daemon: rpc error: code = FailedPrecondition desc = network yxjfuqcxs8dxh35ve3dx1abv9 is in use by service 3f4xbxc52npqc18r9fz1y85bvFailed to remove some resources from stack: func
s@s-GA-78LMT-USB3-6-0:~/github/go/src/github.com/alexellis/faas-cli$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                            PORTS
3f4xbxc52npq        csharp-hello        replicated          1/1                 ems5311/csharp-hello             
l2p8imut0exs        helloc              replicated          1/1                 alexellis/helloc                 
rksxs1ymydok        nodejs-echo         replicated          1/1                 alexellis/faas-nodejs-echo       
pqlk5wrogn9e        ruby-echo           replicated          1/1                 alexellis/ruby-echo              
snhngut32iv8        rust-hello          replicated          1/1                 functions/base:rust-2.7-alpine   
817lknd7aibh        shrink-image        replicated          1/1                 functions/resizer                
xy15uj90hyk1        url-ping            replicated          1/1                 alexellis/faas-url-ping          
```

If this is necessary or by-design, let me know, but in order to remove all functions I have to run `docker service rm` for the remaining containers when I want to update the faas platform.

## Expected Behaviour

All faas functions are removed.

## Current Behaviour

Only starting functions are removed

## Possible Solution

Add all openfaas functions to the docker stack

## Steps to Reproduce (for bugs)

1. Create stack, `./build.sh` in faas repo, `./deploy_stack.sh` to deploy starting functions
2. Deploy more functions from `faas-cli` with `faas-cli build -f samples.yml; faas-cli deploy -f samples.yml`
3. `docker stack rm func`
4. `docker service ls`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.09.0-ce-rc1, build ae21824

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 1604
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Docker stacks are actually built up with labels and metadata injected via the Docker CLI. We don't have access to it at deployment time. If you'd like to remove the functions deployed in your OpenFaaS instance maybe you could create a shell script to filter on network or such?

**Comment by rgee0** [comment]
Building on @alexellis's response, I tend to `rm` containers on the func_function network before running `docker stack rm func`.

`docker ps -a --filter network=func_functions | awk '{print $1}' | xargs docker rm -f`

**Comment by ems5311** [comment]
@alexellis and @rgee0, thanks for your informative responses. Now it makes sense why the stack removal doesn't remove all functions. @rgee0 , thank for that command, I think there's an even slightly better way:

`docker ps -a --filter network=func_functions -q | xargs docker rm -f`

Closing this issue.
--Erich
