### ISSUE TITLE
Amend CONTRIBUTING.md to mandate use of Fixes #issue

### ISSUE THREAD

**Issue by rgee0** [alexellis/faas#191]
Use of GitHub [keyword references](https://help.github.com/articles/closing-issues-using-keywords/) in PR descriptions and/or commit messages

## Expected Behaviour
GitHub has built in functionality which helps project maintainers manage issues.  Encouraging contributors to reference issues in their PR descriptions or or commit messages means that github will be able to automatically close the associated issues once the PR is merged.  This will remove a manual task from the maintainers and enable project focus to remain on current issues 

## Current Behaviour
PRs are merged & some issues remain open until they are manually reviewed and closed.  Contributors potentially focus consideration and effort on issues already addressed.

## Possible Solution
GitHub has built in functionality which helps project maintainers manage issues.  Encouraging contributors to reference issues in their PR descriptions or or commit messages means that github will be able to automatically close the associated issues once the PR is merged.  This will remove a manual task from the maintainers and enable project focus to remain on current issues 

## Context
Reviewing issues already addressed.  Badgering maintainers to close issues I've addressed or know to be addressed.

## Your Environment
N/A

N.B This issue will also act as a test of the built in functionality.

**Comment by alexellis** [comment]
Can Derek help with this?

**Comment by rgee0** [comment]
I thought he might like to check for 'Fixes #' (for example) and flag it if the PR doesn't apparently address an issue.
