### ISSUE TITLE
Proposal: provide solution so the secrets don't end up in source control

### ISSUE THREAD

**Issue by jmkhael** [alexellis/faas#205]
## Expected Behaviour
Add support for adding secrets, without having to commit them to GitHub

## Current Behaviour
Currently, the only way to add secrets is within a stack YAML file.
I cannot just add it to .gitignore, as I need this to build/deploy/...

This usually implies inadvertent commits of secrets in GitHub (slack tokens, mino credentials...)

## Possible Solution
* support secrets or vault
or
* support a way to refactor the secrets into another YAML files which I can include in the stack YAML file

**Comment by alexellis** [comment]
How does this look that I did on my lunch break? https://github.com/alexellis/faas-cli/pull/110

It's available for testing if you can pull and rebuild the `env_file` branch

**Comment by jmkhael** [comment]
Hello @alexellis this works.

One question though, do we have to add the **environment:** part in each file?

**login.yml**
```
environment:
  account: alex.ellis
  secret_key: dogfight
```

**Comment by alexellis** [comment]
I think it's explained in the PR.. did it make sense?

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
@jmkhael yes every external file will look like that:

```
environment:
  account: alex.ellis
  secret_key: dogfight
```

**Comment by alexellis** [comment]
Implemented in https://github.com/alexellis/faas-cli/pull/110
