### ISSUE TITLE
docker-compose.yml cannot use '\t'

### ISSUE THREAD

**Issue by llitfkitfk** [alexellis/faas#24]
when to execute
```
docker stack deploy -c docker-compose.yml func
```

## Expected Behavior

pass 
## Current Behavior

ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 106, column 22

## Possible Solution

#25 
## Steps to Reproduce (for bugs)

1. git clone faas && cd faas && docker stack deploy -c docker-compose.yml func

## Your Environment

* Version used: 17.03.0-ce
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by llitfkitfk** [comment]
#25

**Comment by alexellis** [comment]
Hi please can you edit this issue to use the template provided? As far as I am aware the compose file is working in the master branch

**Comment by llitfkitfk** [comment]
@alexellis  update

**Comment by alexellis** [comment]
I have the same Docker version and cannot reproduce the issue on my Mac laptop or on Play-with-docker.com. I have removed any extra spacing I could find, do you want to try pulling from master again?

**Comment by llitfkitfk** [comment]
tried & works fine

**Comment by loftwah** [comment]
docker-compose up --abort-on-container-exit
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 7, column 1
  
  I managed to get this and it led me here. I can't figure it out for the life of me :(

**Comment by alexellis** [comment]
@loftwah please raise your own issue because there is no swarm support in openfaas, which is what this issue is about. Don't delete any fields in the template when you raise your ticket.
