### ISSUE TITLE
Adding and deleting a single new function without compose

### ISSUE THREAD

**Issue by vielmetti** [alexellis/faas#26]
## Expected Behavior

I expect to be able to add a new function to a running installation without relaunching all of them, but I get an ambiguous error from the docker command I try. Instead I need rerun deploy_stack to relaunch everything.

## Current Behavior

```
Edwards-Air:oblique emv$ docker run --label "function:true" --network func_functions --env "fprocess:oblique" vielmetti/faas-oblique
docker: Error response from daemon: Could not attach to network func_functions: rpc error: code = 7 desc = network func_functions not manually attachable.
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

I expected to be able to add a function to the func_functions network, but was rejected. Is this a Docker issue? Did I get the attach command wrong?

## Context

This might just be a documentation issue, as this was my first go-around at trying this.

My function is in the Docker container vielmetti/faas-oblique, and it implements Brian Eno's "Oblique Strategies" card deck by emitting a random card from that deck as a line of text.

## Your Environment

* Operating System and version: 
Docker Version 17.03.1-ce-rc1-mac3 (15924)
Channel: edge
1795b358d5

**Comment by alexellis** [comment]
To attach a function at runtime you can use the "New function" button on the portal UI at http://localhost:8080/

A HTTP post can also be sent via `curl` etc to the endpoint used by the UI (HTTP post to `/system/functions`)

```
// CreateFunctionRequest create a function in the swarm.
type CreateFunctionRequest struct {
	Service    string `json:"service"`
	Image      string `json:"image"`
	Network    string `json:"network"`
	EnvProcess string `json:"envProcess"`
}
```

**Comment by vielmetti** [comment]
Working! 

![screen shot 2017-03-24 at 10 39 48 am](https://cloud.githubusercontent.com/assets/35047/24299040/41a6cf30-107e-11e7-8c5c-4c2853751087.png)

**Comment by alexellis** [comment]
Great! Here's the `curl` method:

```
curl localhost:8080/system/functions -d '
{"service": "oblique", "image": "vielmetti/faas-oblique", "envProcess": "/usr/bin/oblique", "network": "func_functions"}'
```

**Comment by vielmetti** [comment]
Blog post writeup, which points back here:

http://vielmetti.github.io/post/2017/2017-W12-4-oblique-strategy-as-a-service/

**Comment by alexellis** [comment]
Thanks for this. Do you want to add a link in community.md. Please could you put a screenshot of the Gateway API on your blog post?

**Comment by vielmetti** [comment]
Thanks Alex! I'll add some screen shots and will get the repo set up. When that is all properly handled I will do a PR for community.md .

**Comment by alexellis** [comment]
I've also added the feedback to the TestDrive guide. https://github.com/alexellis/faas/blob/master/TestDrive.md

**Comment by vielmetti** [comment]
Alex, have you seen ever the issue of replicas spinning down? See this snapshot of the two functions I added through the API:

```
ID            NAME                   MODE        REPLICAS  IMAGE
4eg36gwkpx5i  func_base64            replicated  1/1       functions/alpine:latest
9jmsdlqjuobf  func_echoit            replicated  1/1       functions/alpine:latest
eof3v1jxszwl  func_markdown          replicated  1/1       alexellis2/faas-markdownrender:latest
fned1yerhdyf  func_alertmanager      replicated  1/1       quay.io/prometheus/alertmanager:latest
jyymi2er04hx  func_decodebase64      replicated  1/1       functions/alpine:latest
kpbu0ktf0iqc  func_nodeinfo          replicated  1/1       alexellis2/faas-nodeinfo:latest
lj7j5sas6j0q  func_webhookstash      replicated  1/1       alexellis2/faas-webhookstash:latest
pjc92ptpu8vx  func_prometheus        replicated  1/1       quay.io/prometheus/prometheus:latest
pt6kncp6fyc4  func_alexacolorchange  replicated  1/1       alexellis2/faas-alexachangecolorintent:latest
sbzwtyxgotmv  stronghash             replicated  0/1       functions/alpine:latest
se05h62iawvc  func_wordcount         replicated  1/1       functions/alpine:latest
xm4trevb2n2v  func_hubstats          replicated  1/1       alexellis2/faas-dockerhubstats:latest
yithgmf2il1r  oblique                replicated  0/1       vielmetti/faas-oblique:latest
zesojp59a4ao  func_gateway           replicated  1/1       functions/gateway:latest
```

Is the `func_` prefix meaningful in this case to make sure things start up properly, or keep running?

**Comment by alexellis** [comment]
If you enable experimental mode you can look at the logs with `docker service logs`

The `func_` prefix is added by Docker when using the `stack` file to create the initial set of functions, it's not used by FaaS to identify functions.

**Comment by alexellis** [comment]
Docs updated, thanks for this issue @vielmetti . Closing now.
