### ISSUE TITLE
Port to aarch64 (ARMv8, arm64)

### ISSUE THREAD

**Issue by vielmetti** [alexellis/faas#27]
It would be great to get this working on ARMv8.

## Expected Behavior

The goal would be to provide a Dockerfile that enables FaaS on ARMv8 machines, specifically getting the watchdog process running.

## Current Behavior

The biggest challenge I've identified is finding a compact base container that provides a current version of Go to build and run the worker. The aarch64/ubuntu-golang container is more than a year old, for example. https://github.com/aarch64/ubuntu-golang/issues/4

## Possible Solution

Work upstream to get a good aarch64/golang base image, and this becomes nearly trivial.

## Context

Looking to port this environment to the Packet 2A 96-core ARM servers.

**Comment by alexellis** [comment]
An upstream container would be great - I think you already know @tiannon who manages aarch64.

I have my own set of armhf Dockerfiles in this repo -> [docker-arm](https://github.com/alexellis/docker-arm/tree/master/images/armhf) in the interim I'd be happy to have PRs here to create an ARMv8 version of Dockerfiles.

Did the watchdog / gateway build on Packet?

### Steps for porting

*There may be more, but I'd start here:*

* Find base image for Alpine
* Find base image for Golang 1.7.x (or try building with 1.6.4?)
* Port sample functions as per existing .armhf. extensions
* Port other build scripts as per existing .armhf. extensions

Other dependency: Docker 1.13 or newer.

**Comment by vielmetti** [comment]
The base image for Alpine is easy, that's aarch64/alpine.

The base for Golang 1.7.x or 1.8.x can be aarch64/ubuntu + a Go PPA.

I'll make a link from this issue to http://worksonarm.com/faas and chase dependencies there too.

**Comment by vielmetti** [comment]
WIP https://github.com/alexellis/faas/pull/52

**Comment by vielmetti** [comment]
Someone has a Docker build for 17.04-ce as a binary, I'll find that and use it.

**Comment by vielmetti** [comment]
I count 18 files to touch or add from 

https://github.com/alexellis/faas/search?utf8=✓&q=armhf&type=

There might be some refactoring to be done.

**Comment by rgee0** [comment]
[Arm64v8 on docker hub](https://hub.docker.com/r/arm64v8/golang/tags/) is showing recent activity.

Golang 1.7.5 to 1.9 appears to be available.

**Comment by alexellis** [comment]
Yes, that's good. Docker for ARMv8 is broken for Swarm right now, so this is the blocking piece at the moment. You can do a manual build but if 17.07 is fully working we can move forward with this.

**Comment by alexellis** [comment]
Closing - will create new issue when we tackle this.
