### ISSUE TITLE
Pipe the functions?

### ISSUE THREAD

**Issue by bdestombe** [alexellis/faas#53]
I currently haven't tried FaaS yet, but will do asap. I have one question though, something I couldn't make up from the documentation.

Is it currently possible to create pipes? Thus, to link the STDOUT from one function to the STDIN of another function? Would something like this work?

```bash
mkfifo fifo
./process1 argument1 < fifo | ./process2 argument1 > fifo
```
http://stackoverflow.com/questions/5129276/how-to-redirect-stdout-of-2nd-process-back-to-stdin-of-1st-process

Thanks,
Bas

**Comment by aafrey** [comment]
@bdestombe i would be unsure about using unix pipes, but I've done something similar by chaining functions together. My example uses javascript and promises, but i'd think this could be done in any language. check out this FaaS [function ](https://github.com/aafrey/faas-demo/tree/master/src/Logger), index.coffee and faas-chain.coffee specifically for an example.

**Comment by alexellis** [comment]
Hi @bdestombe,

The functions are accessed through the API gateway which is a HTTP endpoint. So for now, you can (pipe) chain functions in two ways:

* Through the client (transform passes back to caller each time - so network trips)
* On the server, a single function calls through to other functions via local network - so less latency

But effectively you are piping. In my Dockercon demo you'll see me do server-side chaining for the Github / Fanclub:

https://github.com/alexellis/faas-dockercon/

**Comment by bdestombe** [comment]
Ah indeed, this makes sense. Thanks, both of you @aafrey and @alexellis. Using a post request over http for chaining several function was indeed what I was looking for.

Thanks,
Bas

**Comment by bdestombe** [comment]
Ah eventually found what I was originally looking for. This example first prints the license file to the stdin of the built-in encrypt-to-base64 function, then passes the encoded string to the the decrypt-from-base64 function and prints it to the stdout. It works on the playground.
 
```bash
cat LICENSE | curl -sX POST http://localhost:8080/function/func_base64 -d "$(</dev/stdin)" | curl -sX POST http://localhost:8080/function/func_decodebase64 -d "$(</dev/stdin)"
```
got some pointers from http://stackoverflow.com/questions/12583930/use-pipe-for-curl-data

**Comment by alexellis** [comment]
I think that can become a bit simpler still. I'll see if I can suggest something in the week

**Comment by alexellis** [comment]
Here we go -

```
# curl -s --data-binary @LICENSE http://localhost:8080/function/func_base64 | curl -s http://localhost:8080/function/func_decodebase64 --data-binary @-
```
