### ISSUE TITLE
Bind mounted config files should be baked into images (wip)

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#57]
Bind mounting config files for Prometheus and AlertManager means it's hard to remotely deploy with docker-machine etc. From: @timhaak

## Possible Solution

Build new images with config added already under functions repo on the Hub. Ideally via auto-build.

**Comment by tieum** [comment]
Another option could be to use docker secrets, see: https://github.com/tieum/faas/commit/0f0fc958bd188440ca4a82567d2dbcfd84696c89

**Comment by alexellis** [comment]
Hi @tieum thanks for getting in touch.

Docker secrets can act as configuration - however it still means keeping the configuration in every FaaS stack. An image with a sensible default built-in has pros and cons - on the pro side you only need a docker-compose.yml file and nothing else - on the cons side you may want to tune the config, then you add your config back in over the top.

I think "configuration" for Swarm will arrive at some point - so that may be a better solution.

Did you have ideas for the rest of the backlog/roadmap/issues list? Have you been using FaaS and the CLI?

**Comment by alexellis** [comment]
@tieum I'll close this issue since we have auto-build for these images now.
