### ISSUE TITLE
Where to find Dockerfile for "Busybox / shell"(functions/alpine:latest)

### ISSUE THREAD

**Issue by ehirdoy** [alexellis/faas#62]
Hi,

I just want to confirm Docker file for https://hub.docker.com/r/functions/alpine/.
Can you git-add this file into repo too?

Thank you for exciting project!!

**Comment by alexellis** [comment]
Hey, you're welcome! 

It's in the samples folder -> https://github.com/alexellis/faas/tree/master/sample-functions/AlpineFunction

Also - I've set up auto-build for this but the name is a bit more verbose -> https://hub.docker.com/r/functions/base/tags/
