### ISSUE TITLE
Questions from Serverless Mingles 

### ISSUE THREAD

**Issue by amirmc** [alexellis/faas#63]
I did a number of Moby Mingles at DockerCon on the topic of Serverless.  During those mingles, I showed people FaaS.  The following are some of the questions that came up during discussions (they're not necessarily FaaS-specific). 

- How does the watchdog work?
- Do I have to have a replica of each function (what if I have thousands)?
    - What about management/discovery of all those functions?
- How do I register a new function?
- Does it work with k8s?

**Comment by alexellis** [comment]
Rough diagram of the Watchdog

<img width="944" alt="screen shot 2017-04-12 at 16 49 20" src="https://cloud.githubusercontent.com/assets/6358735/25360546/8118d0c4-2941-11e7-8430-128139b13c09.png">

**Comment by alexellis** [comment]
Thanks Amir!
