### ISSUE TITLE
Add health check to ARMHF examples

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#72]
## Expected Behavior

Auto-scaling without any drop  in performance

## Current Behavior

Lack of health check (only in arm examples) means that the performance drops and could cause oscillation between replica counts. 

## Possible Solution

* Just need to add `HEALTCHECK CMD` as per 64-bit examples.
* Release new version of Watchdog for ARMHF

**Comment by alexellis** [comment]
https://github.com/alexellis/faas/commit/ac9f2fad32a98f4a2111cedecb48c96b381f55ee

**Comment by alexellis** [comment]
Currently have some issues with Docker CE 17.07 regarding Swarm.. It won't schedule any services on ARM.

**Comment by rgee0** [comment]
I've been looking into this today

**Comment by alexellis** [comment]
@rgee0 I can't seem to assign this to you. Let me know when you have a PR ready.

**Comment by rgee0** [comment]
@alexellis do we consider this closed now?

**Comment by alexellis** [comment]
I'll defer to you.. are you saying there are no more healthchecks needed in the arm examples?

**Comment by rgee0** [comment]
Strange. I replied to this days ago.

All armhf Dockerfiles for the sample functions now include healthcheck.  The base apline Dockerfile also includes healthcheck.  Does this need building and pushing as [functions/alpine:latest-armhf](https://hub.docker.com/r/functions/alpine/tags/)?

**Comment by rgee0** [comment]
@alexellis can this be closed?

**Comment by alexellis** [comment]
functions/alpine:latest-armhf pushed
