### ISSUE TITLE
Get to 1.0 - hard timeouts

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#77]
Hard timeouts should be available for functions to prevent them running beyond desired duration.

## Expected Behavior

I.e. with a hard_timeout of 3 seconds, the process/request should be killed with appropriate HTTP error code after going beyond 3000 ms.

## Current Behavior

Read/Write timeouts are set at the HTTP gateway. 

## Possible Solution

Go routine / timer

**Comment by developius** [comment]
It should also be possible to disable this because you can sometimes have a long running task which you need to know the output from. Although, a better solution would be to have the function fire off a webhook itself so it's possible to get the output.

**Comment by alexellis** [comment]
Yes, it would need to be configurable.

**Comment by xaviator** [comment]
Yes++

**Comment by alexellis** [comment]
@xaviator how are you finding it FaaS?

**Comment by alexellis** [comment]
Anyone want to test a PR for this? @developius @xaviator

**Comment by alexellis** [comment]
Done.. merged.
