### ISSUE TITLE
FaaS Gateway doesn't work with the JSON format

### ISSUE THREAD

**Issue by popey456963** [alexellis/faas#89]
## Expected Behavior
The response should be a JSON-formatted version of the 'text' body.

## Current Behavior
The response is currently `null` or '' for all entries.

## Possible Solution
Convert the textual response to JSON.

## Steps to Reproduce (for bugs)
1. Clone repository on Playing With Docker.
2. Visit the UI page.
3. Select `func_nodeinfo`
4. Select `JSON` response.
5. Note `null` response, test again with `Text` and observe non-`null` response.

Can be reproduced with any of the functions that give an output.

## Context
Just found it playing around with the default FaaS

## Your Environment
* Playing with Docker defaults.

(tagging @developius)

**Comment by alexellis** [comment]
This is only to indicate the client-side rendering of the response. The nodeinfo function is plaintext not JSON hence null.

**Comment by popey456963** [comment]
Ah, is there any way to define a function as only having one response format defined?

**Comment by alexellis** [comment]
@popey456963 welcome to FaaS!

There's some documentation here regarding request/response format -> 

https://github.com/alexellis/faas/tree/master/watchdog

Essentially the default is whatever content-type comes in - also comes out, but you can override the output content-type easily with an environmental variable.

The gateway UI is just a tester page - for most cases you will send in plain text via the UI.

You can also access the functions `curl` or your existing websites/apps/APIs.
