### ISSUE TITLE
Feature Request : FaaS Exec helper

### ISSUE THREAD

**Issue by SylvainDeaure** [alexellis/faas#90]
Ease the use and pipelining of FaaS functions within a shell script.

## Expected Behavior
Pipe from and to FaaS function just as with local utils.

## Current Behavior
We can `curl http://faas... |`  and `| curl -X post -d '$(</dev/stdin)' http://faas` but it feels quite clumsy.
Maybe a little wrapper script or Go app could help, to pipe from/to a single faas-exec without extraneous switches.

## Possible Solution
`cat input.txt | faas-exec func1 | faas-exec -extraparam func2`
`cat input.json | faas-exec func1 | faas-exec func2` (recognizes json and sets header)

Then, chaining FaaS would just be as simple as using core shell utils.

## Context
Trying to demo the ease of use of FaaS by running complex stacks (NLP) within Docker containers, but need some transform steps on data before and after. Need an easy way to chain local and FaaS processes.

**Comment by alexellis** [comment]
Did you wan to have a go at the faas-exec? @SylvainDeaure

**Comment by alexellis** [comment]
Adding label - revisit, will come back to this and close for now. Feel free to re-open and add to the discussion.

**Comment by alexellis** [comment]
It'd be great if you fancied working on this or putting something together.
