### ISSUE TITLE
Feature Request : Visual flow editor

### ISSUE THREAD

**Issue by SylvainDeaure** [alexellis/faas#91]
Design and run complex flows / State machines from FaaS functions.

## Expected Behavior
The idea is similar to amazon step functions and states language.
See https://aws.amazon.com/fr/blogs/aws/new-aws-step-functions-build-distributed-applications-using-visual-workflows/
We could use a visual editor to chain functions.

## Possible Solution
I'm willing to explore the node-red road : the blocks are highly configurable, do have properties, and the resulting flow can be saved as a Json file.
The node red editor is stable and used in several projects.
Functions are blocks, We'll need some structure control as well (parallelism, conditions, retries)

## Context
I'd like to reduce friction when adopting FaaS, and allow non dev to build complex data flows.

Those are just some thoughts right now, but I'll try to demo something.

**Comment by alexellis** [comment]
Thanks for the suggestion. @SylvainDeaure

**Comment by alexellis** [comment]
Adding label - revisit, will come back to this and close for now. Feel free to re-open and add to the discussion.

**Comment by philippe-lavoie** [comment]
fission which is a competitor ( ? ) to open-faas has fission-workflow. Argo is bound to containers but not to specific serverless stack does workflow and has a nice dashboard (just hard to find screenshots in their documentation). I don't think neither of those has a GUI to generate the workflows.

**Comment by philippe-lavoie** [comment]
Just found this video that integrates open faas with node-red

https://www.youtube.com/watch?v=ndv1KFtxT38

Not sure if the integration between node-red and open-faas couldn't be made better. But it does look interesting.
