### ISSUE TITLE
Watchdog Timeouts are multiplied by time.Second^2

### ISSUE THREAD

**Issue by stealthybox** [alexellis/faas#97]
## Expected Behaviour
Watchdog should timeout after 5 seconds (default) or the configured amount of seconds.

## Current Behaviour

Resulting timeout values are very large.
It's not possible to configure small values.
This also affects the default.

## Possible Solution

Remove the extra arithmetic in `main.go`.

## Context

This doesn't look intentional.
I'm not sure what the repercussions are.

I discovered this when copying the timeout configurations over to the Gateway httpServer.

**Comment by alexellis** [comment]
Fixed in #98 thanks for raising the issue.
